Updated patches

diff --git a/OpenFOAM-2.1.1.patch b/OpenFOAM-2.1.1.patch
--- a/OpenFOAM-2.1.1.patch
+++ b/OpenFOAM-2.1.1.patch
@@ -10,6 +10,51 @@ index 7c8bce0..039c370 100644
  platforms/
  
  # reinstate wmake/rules that might look like build folders
+diff --git a/Allwmake b/Allwmake
+index 16edfd1..aed4bd4 100755
+--- a/Allwmake
++++ b/Allwmake
+@@ -8,23 +8,9 @@ wmakeCheckPwd "$WM_PROJECT_DIR" || {
+     exit 1
+ }
+ 
+-[ -n "$FOAM_EXT_LIBBIN" ] || {
+-    echo "Error: FOAM_EXT_LIBBIN not set"
+-    echo "    Check the OpenFOAM entries in your dot-files and source them."
+-    exit 1
+-}
+-
+ # wmake is required for subsequent targets
+ ( cd wmake/src && make )
+ 
+-# build ThirdParty sources
+-if [ -d "$WM_THIRD_PARTY_DIR" ]
+-then
+-    $WM_THIRD_PARTY_DIR/Allwmake
+-else
+-    echo "no ThirdParty sources found - skipping"
+-fi
+-
+ # build OpenFOAM libraries and applications
+ src/Allwmake
+ applications/Allwmake
+diff --git a/applications/Allwmake b/applications/Allwmake
+index 00bc326..9b8bf7d 100755
+--- a/applications/Allwmake
++++ b/applications/Allwmake
+@@ -8,12 +8,6 @@ wmakeCheckPwd "$WM_PROJECT_DIR/applications" || {
+     exit 1
+ }
+ 
+-[ -n "$FOAM_EXT_LIBBIN" ] || {
+-    echo "Error: FOAM_EXT_LIBBIN not set"
+-    echo "    Check the OpenFOAM entries in your dot-files and source them."
+-    exit 1
+-}
+-
+ set -x
+ 
+ wmake all utilities
 diff --git a/applications/solvers/combustion/chemFoam/Make/options b/applications/solvers/combustion/chemFoam/Make/options
 index d5a7a75..4d29d2f 100644
 --- a/applications/solvers/combustion/chemFoam/Make/options
@@ -584,81 +629,107 @@ index 412c2a9..f9c2f73 100644
      const pointField& faceCentres = searchSurf.faceCentres();
  
      List<List<pointIndexHit> > allHitInfo;
-diff --git a/bin/addr2line4Mac.py b/bin/addr2line4Mac.py
+diff --git a/bin/addr2line_mac.py b/bin/addr2line_mac.py
 new file mode 100755
-index 0000000..6adaf9d
+index 0000000..123d2cb
 --- /dev/null
-+++ b/bin/addr2line4Mac.py
-@@ -0,0 +1,69 @@
++++ b/bin/addr2line_mac.py
+@@ -0,0 +1,95 @@
 +#!/usr/bin/env python
 +
-+import sys
-+import subprocess as s
++"""Emulation of addr2line utility."""
 +
-+def gdbIsAvailable():
++
++import subprocess as sp
++
++DEFAULT_ANSWER = "??:0"
++
++def gdb_is_available():
 +    """Check if gdb is installed."""
-+    r = s.call(['which', '-s', 'gdb'])
-+    return r == 0
++    res = sp.call(['which', '-s', 'gdb'])
++    return res == 0
 +
-+def lldbIsAvailable():
++def lldb_is_available():
 +    """Check if lldb is installed."""
-+    r = s.call(['which', '-s', 'lldb'])
-+    return r == 0
++    res = sp.call(['which', '-s', 'lldb'])
++    return res == 0
 +
-+filename=sys.argv[1]
-+address=sys.argv[2]
++def addr2line_gdb(filename, address):
++    """Convert address into line of source file using gdb."""
++    proc = sp.Popen("gdb -batch -x /dev/stdin",
++                    shell=True,
++                    bufsize=0,
++                    stdin=sp.PIPE,
++                    stdout=sp.PIPE,
++                    close_fds=True)
 +
-+answer="??:0"
-+
-+if gdbIsAvailable():
-+    p = s.Popen("gdb -batch -x /dev/stdin",
-+                shell=True,
-+                bufsize=0,
-+                stdin=s.PIPE,
-+                stdout=s.PIPE,
-+                close_fds=True)
-+
-+    (child_stdin, child_stdout) = (p.stdin, p.stdout)
++    (child_stdin, child_stdout) = (proc.stdin, proc.stdout)
 +    child_stdin.write("set sharedlibrary preload-libraries no\n")
-+    child_stdin.write("file "+filename+"\n")
-+    child_stdin.write("info line *"+address+"\n")
-+    result=child_stdout.readline()
-+
++    child_stdin.write("file " + filename + "\n")
++    child_stdin.write("info line *" + address + "\n")
++    res = child_stdout.readline()
 +
 +    import re
-+    match=re.compile('Line (.+) of "(.+)" starts at').match(result)
-+    if match:
-+        answer=match.group(2)+":"+match.group(1)
 +
-+if lldbIsAvailable():
-+    lldb_python_path = s.check_output(['lldb', '-P'])
++    match = re.compile('Line (.+) of "(.+)" starts at').match(res)
++    if match:
++        return match.group(2) + ":" + match.group(1)
++    else:
++        return DEFAULT_ANSWER
++
++def addr2line_lldb(filename, address):
++    """Convert address into line of source file using lldb."""
++    import sys
++
++    lldb_python_path = sp.check_output(['lldb', '-P'])
 +    sys.path.insert(0, lldb_python_path[:-1])
 +
 +    import lldb
 +
-+    address = int(address, 16)
++    addr = int(address, 16)
 +
-+    debugger = lldb.SBDebugger.Create()
-+    debugger.SetAsync(False)
-+    target = debugger.CreateTargetWithFileAndArch(filename,
-+                                                  lldb.LLDB_ARCH_DEFAULT)
++    dbg = lldb.SBDebugger.Create()
++    dbg.SetAsync(False)
++    tgt = dbg.CreateTargetWithFileAndArch(filename,
++                                          lldb.LLDB_ARCH_DEFAULT)
 +
-+    for m in target.module_iter():
-+        sb_addr = m.ResolveFileAddress(address)
-+        resolved_addr = m.ResolveSymbolContextForAddress(
++    for mdl in tgt.module_iter():
++        sb_addr = mdl.ResolveFileAddress(addr)
++        resolved_addr = mdl.ResolveSymbolContextForAddress(
 +            sb_addr,
 +            lldb.eSymbolContextEverything
 +        )
++
 +        if resolved_addr.IsValid():
 +            line_entry = resolved_addr.GetLineEntry()
 +            file_ = line_entry.GetFileSpec()
 +            line = line_entry.GetLine()
 +            if line_entry.ling != 0:
-+                answer = "{0}:{1}".format(file_, line)
++                return "{0}:{1}".format(file_, line)
++    return DEFAULT_ANSWER
 +
-+print answer,
 +
-+sys.exit(255)
++def run():
++    """Determine file and line for a given address."""
++    import sys
++
++    filename = sys.argv[1]
++    address = sys.argv[2]
++
++    answer = DEFAULT_ANSWER
++
++    if gdb_is_available():
++        answer = addr2line_gdb(filename, address)
++
++    if lldb_is_available():
++        answer = addr2line_lldb(filename, address)
++
++    print answer,
++
++    sys.exit(255)
++
++if __name__ == '__main__':
++    run()
 diff --git a/bin/paraFoam b/bin/paraFoam
 index 867212e..4cc926a 100755
 --- a/bin/paraFoam
@@ -676,7 +747,7 @@ index 867212e..4cc926a 100755
  # parse options
  while [ "$#" -gt 0 ]
 diff --git a/etc/bashrc b/etc/bashrc
-index 7968dff..5f3111a 100644
+index 7968dff..c657a2d 100644
 --- a/etc/bashrc
 +++ b/etc/bashrc
 @@ -58,12 +58,11 @@ foamInstall=$HOME/$WM_PROJECT
@@ -704,7 +775,18 @@ index 7968dff..5f3111a 100644
  export WM_MPLIB=OPENMPI
  
  #- Operating System:
-@@ -199,6 +197,11 @@ cleaned=`$foamClean "$LD_LIBRARY_PATH" "$foamOldDirs"` \
+@@ -113,10 +111,6 @@ fi
+ export WM_PROJECT_INST_DIR=$FOAM_INST_DIR
+ export WM_PROJECT_DIR=$WM_PROJECT_INST_DIR/$WM_PROJECT-$WM_PROJECT_VERSION
+ 
+-# Location of third-party software
+-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+-export WM_THIRD_PARTY_DIR=$WM_PROJECT_INST_DIR/ThirdParty-$WM_PROJECT_VERSION
+-
+ # Location of site-specific templates etc
+ # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ # unset is equivalent to $WM_PROJECT_INST_DIR/site
+@@ -199,6 +193,11 @@ cleaned=`$foamClean "$LD_LIBRARY_PATH" "$foamOldDirs"` \
  
  #- Clean MANPATH
  cleaned=`$foamClean "$MANPATH" "$foamOldDirs"` && MANPATH="$cleaned"
@@ -716,7 +798,7 @@ index 7968dff..5f3111a 100644
  
  export PATH LD_LIBRARY_PATH MANPATH
  
-@@ -223,10 +226,13 @@ cleaned=`$foamClean "$PATH"` && PATH="$cleaned"
+@@ -223,10 +222,13 @@ cleaned=`$foamClean "$PATH"` && PATH="$cleaned"
  #- Clean LD_LIBRARY_PATH
  cleaned=`$foamClean "$LD_LIBRARY_PATH"` && LD_LIBRARY_PATH="$cleaned"
  
@@ -824,7 +906,7 @@ index df1dce8..0fafd36 100644
  
  # -----------------------------------------------------------------------------
 diff --git a/etc/config/settings.sh b/etc/config/settings.sh
-index eb1dbe2..388cf2c 100644
+index eb1dbe2..06f9c68 100644
 --- a/etc/config/settings.sh
 +++ b/etc/config/settings.sh
 @@ -46,6 +46,10 @@ _foamAddLib()
@@ -876,7 +958,7 @@ index eb1dbe2..388cf2c 100644
              export WM_COMPILER_LIB_ARCH=64
              export WM_CC='gcc'
              export WM_CXX='g++'
-@@ -93,54 +96,21 @@ Linux)
+@@ -93,54 +96,18 @@ Linux)
              export WM_LDFLAGS='-m64'
              ;;
          *)
@@ -929,9 +1011,6 @@ index eb1dbe2..388cf2c 100644
 -    export WM_CFLAGS='-mabi=64 -fPIC'
 -    export WM_CXXFLAGS='-mabi=64 -fPIC'
 -    export WM_LDFLAGS='-mabi=64 -G0'
-+    #    export WM_COMPILER=
-+    #    export WM_MPLIB=OPENMPI
-+
 +    MACOSX_DEPLOYMENT_TARGET=`sw_vers -productVersion`
      ;;
  
@@ -939,7 +1018,17 @@ index eb1dbe2..388cf2c 100644
  *)    # an unsupported operating system
      cat <<USAGE
  
-@@ -220,116 +190,6 @@ then
+@@ -166,9 +133,6 @@ export WM_OPTIONS=$WM_ARCH$WM_COMPILER$WM_PRECISION_OPTION$WM_COMPILE_OPTION
+ export FOAM_APPBIN=$WM_PROJECT_DIR/platforms/$WM_OPTIONS/bin
+ export FOAM_LIBBIN=$WM_PROJECT_DIR/platforms/$WM_OPTIONS/lib
+ 
+-# external (ThirdParty) libraries
+-export FOAM_EXT_LIBBIN=$WM_THIRD_PARTY_DIR/platforms/$WM_OPTIONS/lib
+-
+ # shared site executables/libraries
+ # similar naming convention as ~OpenFOAM expansion
+ if [ -n "$WM_PROJECT_SITE" ]
+@@ -220,116 +184,6 @@ then
  fi
  
  case "${foamCompiler}" in
@@ -1056,7 +1145,7 @@ index eb1dbe2..388cf2c 100644
  system)
      # okay, use system compiler
      ;;
-@@ -340,27 +200,27 @@ system)
+@@ -340,27 +194,27 @@ system)
  esac
  
  
@@ -1101,7 +1190,7 @@ index eb1dbe2..388cf2c 100644
  
  # enabled if CGAL is available
  if [ "$FOAM_VERBOSE" -a "$PS1" ]
-@@ -375,6 +235,10 @@ then
+@@ -375,6 +229,10 @@ then
      if [ -d "$BOOST_ARCH_PATH" ]
      then
          _foamAddLib $BOOST_ARCH_PATH/lib
@@ -1112,7 +1201,7 @@ index eb1dbe2..388cf2c 100644
      else
          unset BOOST_ARCH_PATH
      fi
-@@ -385,199 +249,23 @@ fi
+@@ -385,199 +243,23 @@ fi
  
  unset boost_version cgal_version
  
@@ -1320,7 +1409,7 @@ index eb1dbe2..388cf2c 100644
  
  # add (non-dummy) MPI implementation
  # dummy MPI already added to LD_LIBRARY_PATH and has no external libraries
-@@ -586,7 +274,11 @@ then
+@@ -586,7 +268,11 @@ then
      _foamAddLib $FOAM_LIBBIN/$FOAM_MPI:$FOAM_EXT_LIBBIN/$FOAM_MPI
  fi
  
@@ -1332,7 +1421,7 @@ index eb1dbe2..388cf2c 100644
  
  # Set the minimum MPI buffer size (used by all platforms except SGI MPI)
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-@@ -598,6 +290,12 @@ then
+@@ -598,6 +284,12 @@ then
  fi
  export MPI_BUFFER_SIZE
  
@@ -1345,6 +1434,23 @@ index eb1dbe2..388cf2c 100644
  
  # cleanup environment:
  # ~~~~~~~~~~~~~~~~~~~~
+diff --git a/src/Allwmake b/src/Allwmake
+index aa17b41..4696526 100755
+--- a/src/Allwmake
++++ b/src/Allwmake
+@@ -9,12 +9,6 @@ wmakeCheckPwd "$WM_PROJECT_DIR/src" || {
+     exit 1
+ }
+ 
+-[ -n "$FOAM_EXT_LIBBIN" ] || {
+-    echo "Error: FOAM_EXT_LIBBIN not set"
+-    echo "    Check the OpenFOAM entries in your dot-files and source them."
+-    exit 1
+-}
+-
+ set -x
+ 
+ # update OpenFOAM version strings if required
 diff --git a/src/OSspecific/POSIX/POSIX.C b/src/OSspecific/POSIX/POSIX.C
 index 3429031..c818aa0 100644
 --- a/src/OSspecific/POSIX/POSIX.C
@@ -1434,7 +1540,7 @@ index bf04835..625f9b6 100644
  // * * * * * * * * * * * * * * * * Constructors  * * * * * * * * * * * * * * //
  
 diff --git a/src/OSspecific/POSIX/printStack.C b/src/OSspecific/POSIX/printStack.C
-index df31b35..250d88b 100644
+index df31b35..4381eb4 100644
 --- a/src/OSspecific/POSIX/printStack.C
 +++ b/src/OSspecific/POSIX/printStack.C
 @@ -31,8 +31,11 @@ License
@@ -1500,7 +1606,7 @@ index df31b35..250d88b 100644
 +#ifndef darwin
              "addr2line -f --demangle=auto --exe "
 +#else
-+            "addr2line4Mac.py "
++            "addr2line_mac.py "
 +#endif
            + filename
            + " "
@@ -1512,7 +1618,7 @@ index df31b35..250d88b 100644
 +#ifndef darwin
              "addr2line -f --demangle=auto --exe "
 +#else
-+            "addr2line4Mac.py "
++            "addr2line_mac.py "
 +#endif
            + filename
            + " "
